[2025-10-28T23:54:00.176+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka manual__2025-10-28T23:53:58.892905+00:00 [queued]>
[2025-10-28T23:54:00.184+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka manual__2025-10-28T23:53:58.892905+00:00 [queued]>
[2025-10-28T23:54:00.185+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-28T23:54:00.199+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ConsumKafka> on 2025-10-28 23:53:58.892905+00:00
[2025-10-28T23:54:00.210+0000] {standard_task_runner.py:60} INFO - Started process 359 to run task
[2025-10-28T23:54:00.213+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_calcul_trajet_kafka', 'ConsumKafka', 'manual__2025-10-28T23:53:58.892905+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/dag1_kafka_processing.py', '--cfg-path', '/tmp/tmpvxkq9sgh']
[2025-10-28T23:54:00.216+0000] {standard_task_runner.py:88} INFO - Job 100: Subtask ConsumKafka
[2025-10-28T23:54:00.279+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka manual__2025-10-28T23:53:58.892905+00:00 [running]> on host 9680281a20bc
[2025-10-28T23:54:00.376+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_calcul_trajet_kafka' AIRFLOW_CTX_TASK_ID='ConsumKafka' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T23:53:58.892905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-28T23:53:58.892905+00:00'
[2025-10-28T23:54:00.382+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:54:00.387+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 9092)]>: Broker version identified as 2.6
[2025-10-28T23:54:00.387+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:54:00.389+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('source',)
[2025-10-28T23:54:00.390+0000] {dag1_kafka_processing.py:71} INFO - Consommateur Kafka créé pour le topic 'source'. En attente de messages...
[2025-10-28T23:54:00.393+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:54:00.394+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:54:00.395+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:54:00.498+0000] {cluster.py:401} INFO - Coordinator for group/***-consumers-dag1 is ('coordinator-1', 'kafka', 9092, None)
[2025-10-28T23:54:00.499+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group ***-consumers-dag1
[2025-10-28T23:54:00.499+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-10-28T23:54:00.500+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group ***-consumers-dag1
[2025-10-28T23:54:00.501+0000] {base.py:419} INFO - Failed to join group ***-consumers-dag1: NodeNotReadyError: coordinator-1
[2025-10-28T23:54:00.502+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-10-28T23:54:00.503+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-10-28T23:54:00.604+0000] {base.py:532} INFO - (Re-)joining group ***-consumers-dag1
[2025-10-28T23:54:00.608+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-60dad56b-30ef-463c-8d51-4ec0fd8c36e1 for group ***-consumers-dag1; will retry join-group
[2025-10-28T23:54:00.609+0000] {base.py:419} INFO - Failed to join group ***-consumers-dag1: [Error 79] MemberIdRequiredError
[2025-10-28T23:54:00.610+0000] {base.py:532} INFO - (Re-)joining group ***-consumers-dag1
[2025-10-28T23:54:01.396+0000] {base.py:594} INFO - Successfully joined group ***-consumers-dag1 <Generation 22 (member_id: kafka-python-2.2.15-60dad56b-30ef-463c-8d51-4ec0fd8c36e1, protocol: range)>
[2025-10-28T23:54:01.401+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('source', 0)]
[2025-10-28T23:54:01.402+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('source', 0),) for group ***-consumers-dag1
[2025-10-28T23:54:04.424+0000] {base.py:951} WARNING - Heartbeat failed for group ***-consumers-dag1 because it is rebalancing
[2025-10-28T23:54:04.427+0000] {consumer.py:365} INFO - Revoking previously assigned partitions (('source', 0),) for group ***-consumers-dag1
[2025-10-28T23:54:04.428+0000] {base.py:532} INFO - (Re-)joining group ***-consumers-dag1
[2025-10-28T23:54:04.431+0000] {base.py:594} INFO - Successfully joined group ***-consumers-dag1 <Generation 23 (member_id: kafka-python-2.2.15-60dad56b-30ef-463c-8d51-4ec0fd8c36e1, protocol: range)>
[2025-10-28T23:54:04.437+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('source', 0)]
[2025-10-28T23:54:04.438+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('source', 0),) for group ***-consumers-dag1
[2025-10-28T23:54:28.515+0000] {base.py:951} WARNING - Heartbeat failed for group ***-consumers-dag1 because it is rebalancing
[2025-10-28T23:54:28.518+0000] {consumer.py:365} INFO - Revoking previously assigned partitions (('source', 0),) for group ***-consumers-dag1
[2025-10-28T23:54:28.519+0000] {base.py:532} INFO - (Re-)joining group ***-consumers-dag1
[2025-10-28T23:54:28.597+0000] {base.py:594} INFO - Successfully joined group ***-consumers-dag1 <Generation 24 (member_id: kafka-python-2.2.15-60dad56b-30ef-463c-8d51-4ec0fd8c36e1, protocol: range)>
[2025-10-28T23:54:28.600+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('source', 0)]
[2025-10-28T23:54:28.601+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('source', 0),) for group ***-consumers-dag1
[2025-10-28T23:54:30.393+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-10-28T23:54:30.394+0000] {base.py:891} INFO - Leaving consumer group (***-consumers-dag1).
[2025-10-28T23:54:30.396+0000] {base.py:906} INFO - LeaveGroup request for group ***-consumers-dag1 returned successfully
[2025-10-28T23:54:30.397+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:54:30.397+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>
[2025-10-28T23:54:30.398+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-10-28T23:54:30.398+0000] {dag1_kafka_processing.py:77} WARNING - Aucun message reçu du topic 'source'. Le DAG s'arrêtera.
[2025-10-28T23:54:30.398+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-28T23:54:30.411+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag1_calcul_trajet_kafka, task_id=ConsumKafka, execution_date=20251028T235358, start_date=20251028T235400, end_date=20251028T235430
[2025-10-28T23:54:30.440+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-28T23:54:30.471+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
